services:
    lupai-mw-core:
        image: lupai-mw-core
        container_name: lupai-mw-core
        build:
            context: .
            dockerfile: ./docker/core/Dockerfile
        volumes:
            - $PWD/resources:/resources
            - $PWD/notebooks:/notebooks
        env_file:
            - .env
        networks:
            - lupai-mw

    lupai-mw-redis:
        image: redis:8.2.1
        container_name: lupai-mw-redis
        volumes:
            - $PWD/resources/cache/redis:/data
        restart: unless-stopped
        networks:
            - lupai-mw

    lupai-mw-mongo:
        image: mongo:8.0.14
        container_name: lupai-mw-mongo
        ports:
            - "27017:27017"
        command: ["mongod", "--wiredTigerCacheSizeGB", "0.4"]
        volumes:
            - $PWD/resources/db/mongo/db:/data/db:z
        deploy:
            resources:
                limits:
                    memory: 512M
        restart: unless-stopped
        networks:
            - lupai-mw

    lupai-mw-qdrant:
        image: qdrant/qdrant:v1.15.4
        container_name: lupai-mw-qdrant
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - ./resources/db/qdrant:/qdrant/storage
        deploy:
            resources:
                limits:
                    memory: 1024M
        restart: unless-stopped
        networks:
            - lupai-mw

    lupai-mw-api:
        image: lupai-mw-api
        container_name: lupai-mw-api
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        volumes:
            - $PWD/resources:/resources
        env_file:
            - .env
        environment:
            - API_PORT=8000
        deploy:
            resources:
                limits:
                    memory: 1536M
        restart: unless-stopped
        networks:
            - lupai-mw

    lupai-mw-mcp:
        image: lupai-mw-mcp
        container_name: lupai-mw-mcp
        build:
            context: .
            dockerfile: ./docker/mcp/Dockerfile
        volumes:
            - $PWD/resources:/resources
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - lupai-mw

networks:
    lupai-mw:
        name: lupai-mw
        driver: bridge
